/*
 *  
 * Home constants
 *
 */

export const category = {
    REQUEST_CATEGORY_PRODUCT : 'REQUEST_CATEGORY_PRODUCT',
    REQUEST_CATEGORY_PRODUCT_SUCCESS: 'REQUEST_CATEGORY_PRODUCT_SUCCESS',
    REQUEST_CATEGORY_PRODUCT_FAIL: 'REQUEST_CATEGORY_PRODUCT_FAIL',
    REQUEST_PRODUCT_DETAIL: 'REQUEST_PRODUCT_DETAIL',
} 
